[build]
  command = "cd website && npm i && npm run build && npm run export"
  publish = "website/out"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"
    # The path to the build directory
	  build_dir_path = "website"
